const HELP_OPTION_FLAGS = ["-h", "--help"];
const VERSION_OPTION_FLAGS = ["-V", "--version"];

const SPECIAL_OPTIONS = [
  ...VERSION_OPTION_FLAGS,
  ...HELP_OPTION_FLAGS,
];

const DEFAULT_VERSION = "0.0.1";

module.exports = {
  HELP_OPTION_FLAGS,
  VERSION_OPTION_FLAGS,
  SPECIAL_OPTIONS,
  DEFAULT_VERSION,
};
